name       : python-certifi
version    : 2022.09.24
release    : 16
source     :
    - https://github.com/certifi/python-certifi/archive/refs/tags/2022.09.24.tar.gz : 8c1db7f2a3b272e8a90b2e1910763930fa81e2512fbb96cb7a25787d63765c78
homepage   : https://github.com/certifi/python-certifi
license    : MPL-2.0
component  : programming.python
summary    : Python package for providing Mozilla's CA Bundle
description: |
    Certifi is a carefully curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. It has been extracted from the Requests project.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
