name       : python-certifi
version    : 2018.4.16
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/c/certifi/certifi-2018.4.16.tar.gz : 13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7
license    : MPL-2.0
component  : programming.python
summary    : Certifi is a carefully curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts
description: |
    Certifi is a carefully curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. It has been extracted from the Requests project.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
