name       : python-certifi
version    : 2022.06.15
release    : 15
source     :
    - https://github.com/certifi/python-certifi/archive/refs/tags/2022.06.15.tar.gz : 3ece28ce4177241cd9f752ef5161cd2c67060b80c73c6bcbdab48e504f9df966
homepage   : https://github.com/certifi/python-certifi
license    : MPL-2.0
component  : programming.python
summary    : Python package for providing Mozilla's CA Bundle
description: |
    Certifi is a carefully curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. It has been extracted from the Requests project.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
